baseURL: "https://abstract-factory.xyz/"
theme: "up-business-theme"
languageCode: "en-us"

title: "Abstract-Factory"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Abstract-Factory"
  description: "It is important for us not only to execute the technical part but also to provide quality expertise and become your partner in the world of software development!"
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "https://www.linkedin.com/company/abstract-factory-xyz/"

  location:
    - "Fort Myers, Florida, United States"
    - "Lviv, Ukraine"

  contact:
    - "CMO: vlevin@abstract-factory.xyz"
    - "CEO: vadym@abstract-factory.xyz"

  copyright: "© 2024 Abstract-Factory All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/how-we-work"
      weight: 2

    - name: "Our team"
      url: "/our-team"
      weight: 3

  buttons:
    - name: "Book a call"
      url: "/lets-talk"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/how-we-work"
      weight: 2

    - name: "Our team"
      url: "/our-team"
      weight: 3

taxonomies:
  series: "series"
  tags: "tags"
